name: psgmx_placement_prep
description: Placement Preparation Program App for PSG Technology - MCA.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.0
  firebase_analytics: ^10.8.0
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http: ^1.1.2
  url_launcher: ^6.2.2
  go_router: ^13.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
